-- TRAZENDO TODOS OS DADOS
SELECT * FROM LIVROS;

-- TRAZENDO O NOME DO LIVRO E DA EDITORA
SELECT LIVRO, EDITORA
FROM LIVROS;

-- TRAZER O NOME DO LIVRO E A UF DOS LIVROS PUBLICADOS POR AUTORES DO SEXO MASCULINO.
SELECT LIVRO, UF
FROM LIVROS
WHERE SEXO = 'M';

-- TRAZER O NOME DO LIVRO E O NUMERO DE PAGINAS DOS LIVROS PUBLICADOS POR AUTORES DO SEXO FEMINICO
SELECT LIVROS, PAGINAS
FROM LIVROS
WHERE SEXO = 'F';

-- TRAZER OS VALORES DOS LIVROS DAS EDITORAS DE SÃO PAULO
SELECT LIROS, VALORES
FROM LIVROS
WHERE EDITORA = 'SP';

-- TRAZER OS DADOS DOS AUTORES DO SEXO MASCULINO QUE TIVERAM LIVROS PUBLICADOS POR SÃO PAULO OU RIO DE JANEIRO
SELECT AUTOR, SEXO, UF
FROM LIVROS
WHERE SEXO = 'M'
AND UF = 'SP'
OR UF = 'RJ';